version: '3.8'
services:
  backend:
    build:
      context: ../backend
    env_file:
      - ../backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    expose:
      - 8000

  frontend:
    build:
      context: ../frontend
    command: /bin/sh -c "vite build && nginx -g 'daemon off;'"
    expose:
      - 80

  nginx:
    image: nginx:1.25
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/dist:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"

  # liminaldb:
  #   image: your/liminaldb:latest
  #   ports:
  #     - "8001:8001"

networks:
  default:
    name: liminal-you-net
